<?php
    $message_from_block = $block->getHelloWorld();
    $array_from_template = $block->getArrayToTemplate();
    $productNameFromCustomBlock = $block->getProductName();
?>

<h1> <?php echo $productNameFromCustomBlock . ' "From The Custom Block". ';?> </h1>

<h1> <?php echo $message_from_block;?> </h1>

<?php foreach ($array_from_template as $element): ?>
    <ul>
        <li><?php echo $element; ?></li>
    </ul>
<?php endforeach; ?>

<h1> <?php echo $this->getShowHello();?> </h1>
<h1> <?php print_r( $this->getShowArray() );?> </h1>
